
INSERT INTO USUARIOS (NOME, EMAIL, PRIORIDADE, SALDO)
VALUES ('Ana Souza',      'ana.souza@email.com',      3, 0);

INSERT INTO USUARIOS (NOME, EMAIL, PRIORIDADE, SALDO)
VALUES ('Bruno Lima',     'bruno.lima@email.com',     3, 0);

INSERT INTO USUARIOS (NOME, EMAIL, PRIORIDADE, SALDO)
VALUES ('Carla Mendes',   'carla.mendes@email.com',   2, 0);

INSERT INTO USUARIOS (NOME, EMAIL, PRIORIDADE, SALDO)
VALUES ('Diego Ferreira', 'diego.ferreira@email.com', 2, 0);

INSERT INTO USUARIOS (NOME, EMAIL, PRIORIDADE, SALDO)
VALUES ('Elena Rocha',    'elena.rocha@email.com',    1, 0);

INSERT INTO USUARIOS (NOME, EMAIL, PRIORIDADE, SALDO)
VALUES ('Fabio Castro',   'fabio.castro@email.com',   1, 0);

INSERT INTO USUARIOS (NOME, EMAIL, PRIORIDADE, SALDO)
VALUES ('Gabi Nunes',     'gabi.nunes@email.com',     2, 0);

INSERT INTO USUARIOS (NOME, EMAIL, PRIORIDADE, SALDO)
VALUES ('Hugo Teixeira',  'hugo.teixeira@email.com',  1, 0);


INSERT INTO INSCRICOES (USUARIO_ID, STATUS, VALOR_PAGO, TIPO) VALUES (1, 'PRESENT',   150.00, 'PADRAO');
INSERT INTO INSCRICOES (USUARIO_ID, STATUS, VALOR_PAGO, TIPO) VALUES (1, 'PRESENT',   200.00, 'PADRAO');
INSERT INTO INSCRICOES (USUARIO_ID, STATUS, VALOR_PAGO, TIPO) VALUES (1, 'PRESENT',   180.00, 'PADRAO');
INSERT INTO INSCRICOES (USUARIO_ID, STATUS, VALOR_PAGO, TIPO) VALUES (1, 'PRESENT',   120.00, 'PADRAO');

INSERT INTO INSCRICOES (USUARIO_ID, STATUS, VALOR_PAGO, TIPO) VALUES (2, 'PRESENT',   300.00, 'PADRAO');
INSERT INTO INSCRICOES (USUARIO_ID, STATUS, VALOR_PAGO, TIPO) VALUES (2, 'PRESENT',   250.00, 'PADRAO');
INSERT INTO INSCRICOES (USUARIO_ID, STATUS, VALOR_PAGO, TIPO) VALUES (2, 'PRESENT',   200.00, 'PADRAO');
INSERT INTO INSCRICOES (USUARIO_ID, STATUS, VALOR_PAGO, TIPO) VALUES (2, 'PRESENT',   150.00, 'PADRAO');
-- Inscrição cancelada: NÃO entra no cursor (STATUS <> 'PRESENT')
INSERT INTO INSCRICOES (USUARIO_ID, STATUS, VALOR_PAGO, TIPO) VALUES (2, 'CANCELADO',  80.00, 'PADRAO');


INSERT INTO INSCRICOES (USUARIO_ID, STATUS, VALOR_PAGO, TIPO) VALUES (3, 'PRESENT',   500.00, 'VIP');
INSERT INTO INSCRICOES (USUARIO_ID, STATUS, VALOR_PAGO, TIPO) VALUES (3, 'PRESENT',   120.00, 'VIP');


INSERT INTO INSCRICOES (USUARIO_ID, STATUS, VALOR_PAGO, TIPO) VALUES (4, 'PRESENT',   600.00, 'VIP');
INSERT INTO INSCRICOES (USUARIO_ID, STATUS, VALOR_PAGO, TIPO) VALUES (4, 'PRESENT',   200.00, 'PADRAO');


INSERT INTO INSCRICOES (USUARIO_ID, STATUS, VALOR_PAGO, TIPO) VALUES (5, 'PRESENT',   350.00, 'PADRAO');
INSERT INTO INSCRICOES (USUARIO_ID, STATUS, VALOR_PAGO, TIPO) VALUES (5, 'PENDENTE',  200.00, 'PADRAO');

INSERT INTO INSCRICOES (USUARIO_ID, STATUS, VALOR_PAGO, TIPO) VALUES (6, 'PRESENT',   410.00, 'PADRAO');
INSERT INTO INSCRICOES (USUARIO_ID, STATUS, VALOR_PAGO, TIPO) VALUES (6, 'PRESENT',   190.00, 'PADRAO');


INSERT INTO INSCRICOES (USUARIO_ID, STATUS, VALOR_PAGO, TIPO) VALUES (7, 'PRESENT',   275.00, 'PADRAO');


INSERT INTO INSCRICOES (USUARIO_ID, STATUS, VALOR_PAGO, TIPO) VALUES (8, 'PRESENT',   130.00, 'PADRAO');
INSERT INTO INSCRICOES (USUARIO_ID, STATUS, VALOR_PAGO, TIPO) VALUES (8, 'CANCELADO',  50.00, 'PADRAO');

COMMIT;

PROMPT Dados inseridos com sucesso!
PROMPT
PROMPT Cenarios cobertos:
PROMPT   A) Ana Souza e Bruno Lima  : 4 presencas cada  -> cashback 25%
PROMPT   B) Carla Mendes e Diego    : ingresso VIP       -> cashback 20%
PROMPT   C) Elena, Fabio, Gabi, Hugo: taxa piso          -> cashback 10%
PROMPT
PROMPT Conferencia dos dados inseridos:

SELECT
    U.NOME,
    U.PRIORIDADE,
    COUNT(CASE WHEN I.STATUS = 'PRESENT' THEN 1 END)                  AS presencas_present,
    MAX(I.TIPO)                                                        AS tipo_max,
    NVL(SUM(CASE WHEN I.STATUS = 'PRESENT' THEN I.VALOR_PAGO END), 0) AS total_present
FROM USUARIOS U
JOIN INSCRICOES I ON U.ID = I.USUARIO_ID
GROUP BY U.NOME, U.PRIORIDADE
ORDER BY U.PRIORIDADE DESC, U.NOME;
